import { RotateCcwIcon } from "lucide-react";
import ShikiHighlighter from "#/lib/shiki";
import { Button } from "#/components/ai/button";
import { Chip } from "#/components/ai/chip";
import {
  Console,
  ConsoleContent,
  ConsoleEntry,
  ConsoleList,
  ConsoleSource,
  ConsoleTimestamp,
} from "#/components/ai/console";
import {
  Sandbox,
  SandboxAction,
  SandboxContent,
  SandboxHeader,
  SandboxPanel,
  SandboxTab,
  SandboxTabs,
  SandboxTabsList,
  SandboxTitle,
  SandboxTrigger,
} from "#/components/ai/sandbox";

const code = `// generated by the model, executed in the sandbox
const orders = await api.orders.recent({ days: 7 });
const byRegion = new Map<string, number>();
for (const order of orders) {
  byRegion.set(order.region, (byRegion.get(order.region) ?? 0) + order.total);
}
console.log("regions:", byRegion.size);
return Object.fromEntries(byRegion);`;

const result = `{
  "us-east": 18420.55,
  "us-west": 12903.10,
  "eu":      9821.40
}`;

export default function CodeMode() {
  return (
    <div className="mx-auto max-w-2xl">
      <Sandbox state="success" defaultOpen>
        <SandboxHeader>
          <SandboxTrigger>
            <SandboxTitle>execute_typescript</SandboxTitle>
            <Chip size="sm" className="text-emerald-500">
              success
            </Chip>
          </SandboxTrigger>
          <SandboxAction>
            <Button variant="ghost" iconOnly aria-label="Re-run">
              <RotateCcwIcon />
            </Button>
          </SandboxAction>
        </SandboxHeader>
        <SandboxContent>
          <SandboxTabs defaultValue="result">
            <SandboxTabsList>
              <SandboxTab value="code">Code</SandboxTab>
              <SandboxTab value="logs">Logs</SandboxTab>
              <SandboxTab value="result">Result</SandboxTab>
            </SandboxTabsList>
            <SandboxPanel value="code">
              <ShikiHighlighter
                language="ts"
                theme={{ light: "github-light", dark: "github-dark" }}
                defaultColor="light"
                addDefaultStyles={false}
                showLanguage={false}
                className="text-sm font-mono [&_pre]:bg-transparent! [&_pre]:outline-none!"
              >
                {code}
              </ShikiHighlighter>
            </SandboxPanel>
            <SandboxPanel value="logs" className="p-0">
              <Console className="h-56">
                <ConsoleContent>
                  <ConsoleList>
                    <ConsoleEntry level="info">
                      <ConsoleTimestamp>09:21:04</ConsoleTimestamp>
                      <span className="min-w-0 flex-1">
                        external_call api.orders.recent
                      </span>
                      <ConsoleSource>code_mode</ConsoleSource>
                    </ConsoleEntry>
                    <ConsoleEntry level="info">
                      <ConsoleTimestamp>09:21:05</ConsoleTimestamp>
                      <span className="min-w-0 flex-1">
                        external_result 142 orders
                      </span>
                      <ConsoleSource>code_mode</ConsoleSource>
                    </ConsoleEntry>
                    <ConsoleEntry level="log">
                      <ConsoleTimestamp>09:21:05</ConsoleTimestamp>
                      <span className="min-w-0 flex-1">regions: 3</span>
                    </ConsoleEntry>
                  </ConsoleList>
                </ConsoleContent>
              </Console>
            </SandboxPanel>
            <SandboxPanel value="result">
              <pre className="text-sm font-mono text-foreground">{result}</pre>
            </SandboxPanel>
          </SandboxTabs>
        </SandboxContent>
      </Sandbox>
    </div>
  );
}
