/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExplorerRouteImport } from './routes/_explorer'
import { Route as ExplorerIndexRouteImport } from './routes/_explorer.index'
import { Route as ExplorerIntroductionRouteImport } from './routes/_explorer.introduction'
import { Route as ExplorerInstallationRouteImport } from './routes/_explorer.installation'
import { Route as ExplorerComponentIndexRouteImport } from './routes/_explorer.$component.index'
import { Route as DemoComponentDemoRouteImport } from './routes/demo.$component.$demo'
import { Route as ExplorerComponentDemoRouteImport } from './routes/_explorer.$component.$demo'

const ExplorerRoute = ExplorerRouteImport.update({
  id: '/_explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerIndexRoute = ExplorerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExplorerRoute,
} as any)
const ExplorerIntroductionRoute = ExplorerIntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => ExplorerRoute,
} as any)
const ExplorerInstallationRoute = ExplorerInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => ExplorerRoute,
} as any)
const ExplorerComponentIndexRoute = ExplorerComponentIndexRouteImport.update({
  id: '/$component/',
  path: '/$component/',
  getParentRoute: () => ExplorerRoute,
} as any)
const DemoComponentDemoRoute = DemoComponentDemoRouteImport.update({
  id: '/demo/$component/$demo',
  path: '/demo/$component/$demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerComponentDemoRoute = ExplorerComponentDemoRouteImport.update({
  id: '/$component/$demo',
  path: '/$component/$demo',
  getParentRoute: () => ExplorerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ExplorerIndexRoute
  '/installation': typeof ExplorerInstallationRoute
  '/introduction': typeof ExplorerIntroductionRoute
  '/$component/$demo': typeof ExplorerComponentDemoRoute
  '/demo/$component/$demo': typeof DemoComponentDemoRoute
  '/$component/': typeof ExplorerComponentIndexRoute
}
export interface FileRoutesByTo {
  '/installation': typeof ExplorerInstallationRoute
  '/introduction': typeof ExplorerIntroductionRoute
  '/': typeof ExplorerIndexRoute
  '/$component/$demo': typeof ExplorerComponentDemoRoute
  '/demo/$component/$demo': typeof DemoComponentDemoRoute
  '/$component': typeof ExplorerComponentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_explorer': typeof ExplorerRouteWithChildren
  '/_explorer/installation': typeof ExplorerInstallationRoute
  '/_explorer/introduction': typeof ExplorerIntroductionRoute
  '/_explorer/': typeof ExplorerIndexRoute
  '/_explorer/$component/$demo': typeof ExplorerComponentDemoRoute
  '/demo/$component/$demo': typeof DemoComponentDemoRoute
  '/_explorer/$component/': typeof ExplorerComponentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/installation'
    | '/introduction'
    | '/$component/$demo'
    | '/demo/$component/$demo'
    | '/$component/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/installation'
    | '/introduction'
    | '/'
    | '/$component/$demo'
    | '/demo/$component/$demo'
    | '/$component'
  id:
    | '__root__'
    | '/_explorer'
    | '/_explorer/installation'
    | '/_explorer/introduction'
    | '/_explorer/'
    | '/_explorer/$component/$demo'
    | '/demo/$component/$demo'
    | '/_explorer/$component/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExplorerRoute: typeof ExplorerRouteWithChildren
  DemoComponentDemoRoute: typeof DemoComponentDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_explorer': {
      id: '/_explorer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explorer/': {
      id: '/_explorer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ExplorerIndexRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/_explorer/introduction': {
      id: '/_explorer/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof ExplorerIntroductionRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/_explorer/installation': {
      id: '/_explorer/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof ExplorerInstallationRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/_explorer/$component/': {
      id: '/_explorer/$component/'
      path: '/$component'
      fullPath: '/$component/'
      preLoaderRoute: typeof ExplorerComponentIndexRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/demo/$component/$demo': {
      id: '/demo/$component/$demo'
      path: '/demo/$component/$demo'
      fullPath: '/demo/$component/$demo'
      preLoaderRoute: typeof DemoComponentDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explorer/$component/$demo': {
      id: '/_explorer/$component/$demo'
      path: '/$component/$demo'
      fullPath: '/$component/$demo'
      preLoaderRoute: typeof ExplorerComponentDemoRouteImport
      parentRoute: typeof ExplorerRoute
    }
  }
}

interface ExplorerRouteChildren {
  ExplorerInstallationRoute: typeof ExplorerInstallationRoute
  ExplorerIntroductionRoute: typeof ExplorerIntroductionRoute
  ExplorerIndexRoute: typeof ExplorerIndexRoute
  ExplorerComponentDemoRoute: typeof ExplorerComponentDemoRoute
  ExplorerComponentIndexRoute: typeof ExplorerComponentIndexRoute
}

const ExplorerRouteChildren: ExplorerRouteChildren = {
  ExplorerInstallationRoute: ExplorerInstallationRoute,
  ExplorerIntroductionRoute: ExplorerIntroductionRoute,
  ExplorerIndexRoute: ExplorerIndexRoute,
  ExplorerComponentDemoRoute: ExplorerComponentDemoRoute,
  ExplorerComponentIndexRoute: ExplorerComponentIndexRoute,
}

const ExplorerRouteWithChildren = ExplorerRoute._addFileChildren(
  ExplorerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ExplorerRoute: ExplorerRouteWithChildren,
  DemoComponentDemoRoute: DemoComponentDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
