/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ExplorerRouteImport } from './routes/_explorer'
import { Route as ExplorerIndexRouteImport } from './routes/_explorer.index'
import { Route as ApiTanstackAiKeyRouteImport } from './routes/api.tanstack-ai-key'
import { Route as ApiTanstackAiChatRouteImport } from './routes/api.tanstack-ai-chat'
import { Route as ExplorerIntroductionRouteImport } from './routes/_explorer.introduction'
import { Route as ExplorerComponentIndexRouteImport } from './routes/_explorer.$component.index'
import { Route as DemoComponentDemoRouteImport } from './routes/demo.$component.$demo'
import { Route as ExplorerInstallationChar123FrameworkChar125RouteImport } from './routes/_explorer.installation.{-$framework}'
import { Route as ExplorerComponentDemoRouteImport } from './routes/_explorer.$component.$demo'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/_explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerIndexRoute = ExplorerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExplorerRoute,
} as any)
const ApiTanstackAiKeyRoute = ApiTanstackAiKeyRouteImport.update({
  id: '/api/tanstack-ai-key',
  path: '/api/tanstack-ai-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTanstackAiChatRoute = ApiTanstackAiChatRouteImport.update({
  id: '/api/tanstack-ai-chat',
  path: '/api/tanstack-ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerIntroductionRoute = ExplorerIntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => ExplorerRoute,
} as any)
const ExplorerComponentIndexRoute = ExplorerComponentIndexRouteImport.update({
  id: '/$component/',
  path: '/$component/',
  getParentRoute: () => ExplorerRoute,
} as any)
const DemoComponentDemoRoute = DemoComponentDemoRouteImport.update({
  id: '/demo/$component/$demo',
  path: '/demo/$component/$demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerInstallationChar123FrameworkChar125Route =
  ExplorerInstallationChar123FrameworkChar125RouteImport.update({
    id: '/installation/{-$framework}',
    path: '/installation/{-$framework}',
    getParentRoute: () => ExplorerRoute,
  } as any)
const ExplorerComponentDemoRoute = ExplorerComponentDemoRouteImport.update({
  id: '/$component/$demo',
  path: '/$component/$demo',
  getParentRoute: () => ExplorerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ExplorerIndexRoute
  '/showcase': typeof ShowcaseRoute
  '/introduction': typeof ExplorerIntroductionRoute
  '/api/tanstack-ai-chat': typeof ApiTanstackAiChatRoute
  '/api/tanstack-ai-key': typeof ApiTanstackAiKeyRoute
  '/$component/$demo': typeof ExplorerComponentDemoRoute
  '/installation/{-$framework}': typeof ExplorerInstallationChar123FrameworkChar125Route
  '/demo/$component/$demo': typeof DemoComponentDemoRoute
  '/$component/': typeof ExplorerComponentIndexRoute
}
export interface FileRoutesByTo {
  '/showcase': typeof ShowcaseRoute
  '/introduction': typeof ExplorerIntroductionRoute
  '/api/tanstack-ai-chat': typeof ApiTanstackAiChatRoute
  '/api/tanstack-ai-key': typeof ApiTanstackAiKeyRoute
  '/': typeof ExplorerIndexRoute
  '/$component/$demo': typeof ExplorerComponentDemoRoute
  '/installation/{-$framework}': typeof ExplorerInstallationChar123FrameworkChar125Route
  '/demo/$component/$demo': typeof DemoComponentDemoRoute
  '/$component': typeof ExplorerComponentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_explorer': typeof ExplorerRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/_explorer/introduction': typeof ExplorerIntroductionRoute
  '/api/tanstack-ai-chat': typeof ApiTanstackAiChatRoute
  '/api/tanstack-ai-key': typeof ApiTanstackAiKeyRoute
  '/_explorer/': typeof ExplorerIndexRoute
  '/_explorer/$component/$demo': typeof ExplorerComponentDemoRoute
  '/_explorer/installation/{-$framework}': typeof ExplorerInstallationChar123FrameworkChar125Route
  '/demo/$component/$demo': typeof DemoComponentDemoRoute
  '/_explorer/$component/': typeof ExplorerComponentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/showcase'
    | '/introduction'
    | '/api/tanstack-ai-chat'
    | '/api/tanstack-ai-key'
    | '/$component/$demo'
    | '/installation/{-$framework}'
    | '/demo/$component/$demo'
    | '/$component/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/showcase'
    | '/introduction'
    | '/api/tanstack-ai-chat'
    | '/api/tanstack-ai-key'
    | '/'
    | '/$component/$demo'
    | '/installation/{-$framework}'
    | '/demo/$component/$demo'
    | '/$component'
  id:
    | '__root__'
    | '/_explorer'
    | '/showcase'
    | '/_explorer/introduction'
    | '/api/tanstack-ai-chat'
    | '/api/tanstack-ai-key'
    | '/_explorer/'
    | '/_explorer/$component/$demo'
    | '/_explorer/installation/{-$framework}'
    | '/demo/$component/$demo'
    | '/_explorer/$component/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExplorerRoute: typeof ExplorerRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRoute
  ApiTanstackAiChatRoute: typeof ApiTanstackAiChatRoute
  ApiTanstackAiKeyRoute: typeof ApiTanstackAiKeyRoute
  DemoComponentDemoRoute: typeof DemoComponentDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explorer': {
      id: '/_explorer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explorer/': {
      id: '/_explorer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ExplorerIndexRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/api/tanstack-ai-key': {
      id: '/api/tanstack-ai-key'
      path: '/api/tanstack-ai-key'
      fullPath: '/api/tanstack-ai-key'
      preLoaderRoute: typeof ApiTanstackAiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tanstack-ai-chat': {
      id: '/api/tanstack-ai-chat'
      path: '/api/tanstack-ai-chat'
      fullPath: '/api/tanstack-ai-chat'
      preLoaderRoute: typeof ApiTanstackAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explorer/introduction': {
      id: '/_explorer/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof ExplorerIntroductionRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/_explorer/$component/': {
      id: '/_explorer/$component/'
      path: '/$component'
      fullPath: '/$component/'
      preLoaderRoute: typeof ExplorerComponentIndexRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/demo/$component/$demo': {
      id: '/demo/$component/$demo'
      path: '/demo/$component/$demo'
      fullPath: '/demo/$component/$demo'
      preLoaderRoute: typeof DemoComponentDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explorer/installation/{-$framework}': {
      id: '/_explorer/installation/{-$framework}'
      path: '/installation/{-$framework}'
      fullPath: '/installation/{-$framework}'
      preLoaderRoute: typeof ExplorerInstallationChar123FrameworkChar125RouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/_explorer/$component/$demo': {
      id: '/_explorer/$component/$demo'
      path: '/$component/$demo'
      fullPath: '/$component/$demo'
      preLoaderRoute: typeof ExplorerComponentDemoRouteImport
      parentRoute: typeof ExplorerRoute
    }
  }
}

interface ExplorerRouteChildren {
  ExplorerIntroductionRoute: typeof ExplorerIntroductionRoute
  ExplorerIndexRoute: typeof ExplorerIndexRoute
  ExplorerComponentDemoRoute: typeof ExplorerComponentDemoRoute
  ExplorerInstallationChar123FrameworkChar125Route: typeof ExplorerInstallationChar123FrameworkChar125Route
  ExplorerComponentIndexRoute: typeof ExplorerComponentIndexRoute
}

const ExplorerRouteChildren: ExplorerRouteChildren = {
  ExplorerIntroductionRoute: ExplorerIntroductionRoute,
  ExplorerIndexRoute: ExplorerIndexRoute,
  ExplorerComponentDemoRoute: ExplorerComponentDemoRoute,
  ExplorerInstallationChar123FrameworkChar125Route:
    ExplorerInstallationChar123FrameworkChar125Route,
  ExplorerComponentIndexRoute: ExplorerComponentIndexRoute,
}

const ExplorerRouteWithChildren = ExplorerRoute._addFileChildren(
  ExplorerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ExplorerRoute: ExplorerRouteWithChildren,
  ShowcaseRoute: ShowcaseRoute,
  ApiTanstackAiChatRoute: ApiTanstackAiChatRoute,
  ApiTanstackAiKeyRoute: ApiTanstackAiKeyRoute,
  DemoComponentDemoRoute: DemoComponentDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
